---
title: "Instacart Interactive Dashboard"
author: "Sukhman Parhar"
date: "2025-10-27"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

These are some plots that I made in P8105: Data Science I based on the `Instacart` data set.

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(p8105.datasets)
library(flexdashboard)

data("instacart")

instacart = instacart |>
  mutate(order_dow = factor(order_dow, 
                            labels = c("Sunday", "Monday", "Tuesday", "Wednesday", 
                                       "Thursday", "Friday", "Saturday")))
```

Column {data-width=650}
-----------------------------------------------------------------------

### Order Counts (for Aisles with >10k Orders)

```{r Top_aisles, echo=FALSE}
library(tidyverse)
library(plotly)

aisle_counts <- instacart |>
  count(aisle, sort = TRUE) |>
  filter(n > 10000) |>
  arrange(desc(n)) |>
  mutate(
    aisle = factor(aisle, levels = aisle),  # order properly
    aisle = as.character(aisle),            # then convert to character
    n = as.numeric(n)
  )

aisle_plot <- plot_ly(
  data = aisle_counts,
  x = ~n,
  y = ~aisle,
  type = "bar",
  orientation = "h",
  color = ~n,
  colors = "plasma"   
) |>
  layout(
    title = "Order Counts (for Aisles with >10k Orders)",
    xaxis = list(title = "Order Count"),
    yaxis = list(
      title = "Aisle",
      categoryorder = "array",
      categoryarray = aisle_counts$aisle
    ),
    showlegend = FALSE
  )

aisle_plot

```

Column {data-width=350}
-----------------------------------------------------------------------

### Orders by Hour of Day

```{r AVG_hours, echo=FALSE}
plot_ly(
data = instacart,
x = ~order_hour_of_day,
type = "histogram",
nbinsx = 24,
marker = list(color = "#2E8B75")
) |>
layout(
title = "Distribution of Orders by Hour of Day",
xaxis = list(title = "Hour of Day (0–23)"),
yaxis = list(title = "Number of Orders")
)

```

### Reorder Rate by Day

```{r reorder, echo=FALSE}
reorder_day <- instacart |>
group_by(order_dow) |>
summarize(mean_reordered = mean(reordered, na.rm = TRUE))

plot_ly(
data = reorder_day,
x = ~order_dow,
y = ~mean_reordered,
type = "scatter",
mode = "lines+markers",
line = list(color = "#4B0082", width = 3)
) |>
layout(
title = "Average Reorder Rate by Day of Week",
xaxis = list(title = "Day of Week"),
yaxis = list(title = "Reorder Rate (0–1)")
)

```